IF OBJECT_ID(N'MySequence', N'SO') IS NOT NULL DROP SEQUENCE MySequence;

CREATE SEQUENCE MySequence AS INT
  MINVALUE 1
  CYCLE;

SELECT NEXT VALUE FOR MySequence;
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);
SELECT POWER(NEXT VALUE FOR MySequence,NEXT VALUE FOR MySequence);

IF OBJECT_ID(N'MySequence', N'SO') IS NOT NULL DROP SEQUENCE MySequence;
